import type { Language } from "./i18n";

export const GAMEPLAY_TEXT = {
  pt: {
    menuLead: "DOMINE A ARENA, EVOLUA SEU ARSENAL E SOBREVIVA AO SHOGUN.",
    move: "MOVER", aim: "MIRAR", attack: "ATACAR", dash: "DASH", swap: "TROCAR ARMA", shop: "LOJA",
    moveHelp: "WASD ou setas", aimHelp: "Mova o mouse", attackHelp: "M1, Espaço ou J", dashHelp: "Shift, K ou botão direito",
    swapHelp: "1-4, Q/E ou scroll", shopHelp: "Abre ao terminar cada onda. Gaste moedas antes de avançar.",
    touchMove: "JOYSTICK ESQUERDO", touchAim: "TOQUE À DIREITA", touchAttack: "SEGURE À DIREITA", touchDash: "BOTÃO DASH", touchSwap: "TOQUE NO SLOT",
    tutorialTitle: "COMO SOBREVIVER", tutorialLead: "Aprenda estes comandos antes da primeira onda.",
    dontShow: "NÃO MOSTRAR NOVAMENTE", begin: "COMEÇAR ONDA 1", shopSoon: "LOJA APÓS A ONDA",
    upgrades: "UPGRADES DA ARMA", damage: "DANO", speed: "VELOC. ATAQUE", range: "ALCANCE", form: "FORMA",
    level: "NV.", max: "MÁX.", improve: "MELHORAR", evolved: "EVOLUÍDA", formLocked: "SÓ KATANA, ARCO, MARTELO, LIVRO E CAJADO EVOLUEM",
    book: "LIVRO ARCANO", bookDesc: "Conjura magia em cone. Escolha o elemento para controlar a arena.", staff: "CAJADO DE INVOCAÇÃO", staffDesc: "Invoca aliados azuis. Evolua para reviver inimigos como servos necromantes.", necromancerStaff: "CAJADO NECROMANTE",
    magic: "MAGIA", fire: "FOGO", fireDesc: "Alto dano imediato e queimadura. Alcance curto.",
    ice: "GELO", iceDesc: "Dano mínimo; congela 2s e aplica lentidão por 5s.",
    poison: "VENENO", poisonDesc: "Pouco impacto, mas dano massivo ao longo do tempo.",
    water: "ÁGUA", waterDesc: "Pouco dano e forte repulsão de inimigos.",
    shieldHint: "BLOQUEIA E REPELE NA DIREÇÃO DA MIRA. M1 REFLETE PROJÉTEIS.",
    weaponLevel: "NÍVEL DA ARMA", automaticPistol: "PISTOLA AUTOMÁTICA", titanHammer: "MARTELO TITÃ",
  },
  en: {
    menuLead: "MASTER THE ARENA, EVOLVE YOUR ARSENAL, AND SURVIVE THE SHOGUN.",
    move: "MOVE", aim: "AIM", attack: "ATTACK", dash: "DASH", swap: "SWAP WEAPON", shop: "SHOP",
    moveHelp: "WASD or arrows", aimHelp: "Move the mouse", attackHelp: "M1, Space, or J", dashHelp: "Shift, K, or right click",
    swapHelp: "1-4, Q/E, or wheel", shopHelp: "Opens after every wave. Spend coins before continuing.",
    touchMove: "LEFT JOYSTICK", touchAim: "TOUCH RIGHT SIDE", touchAttack: "HOLD RIGHT SIDE", touchDash: "DASH BUTTON", touchSwap: "TAP A SLOT",
    tutorialTitle: "HOW TO SURVIVE", tutorialLead: "Learn these controls before the first wave.",
    dontShow: "DO NOT SHOW AGAIN", begin: "START WAVE 1", shopSoon: "SHOP AFTER WAVE",
    upgrades: "WEAPON UPGRADES", damage: "DAMAGE", speed: "ATTACK SPEED", range: "RANGE", form: "FORM",
    level: "LV.", max: "MAX", improve: "UPGRADE", evolved: "EVOLVED", formLocked: "ONLY KATANA, BOW, HAMMER, BOOK AND STAFF EVOLVE",
    book: "ARCANE BOOK", bookDesc: "Casts magic in a cone. Choose an element to control the arena.",
    magic: "MAGIC", fire: "FIRE", fireDesc: "High impact and burn damage. Short range.",
    ice: "ICE", iceDesc: "Tiny damage; freezes for 2s and slows for 5s.",
    poison: "POISON", poisonDesc: "Low impact, massive damage over time.",
    water: "WATER", waterDesc: "Low damage with powerful enemy knockback.",
    shieldHint: "BLOCKS AND REPELS TOWARD YOUR AIM. M1 REFLECTS PROJECTILES.",
    weaponLevel: "WEAPON LEVEL", automaticPistol: "AUTOMATIC PISTOL", titanHammer: "TITAN HAMMER", staff: "SUMMONING STAFF", staffDesc: "Summons blue allies and revives enemies when evolved.", necromancerStaff: "NECROMANCER STAFF",
  },
  fr: {
    menuLead: "MAÎTRISEZ L'ARÈNE, AMÉLIOREZ VOTRE ARSENAL ET SURVIVEZ AU SHOGUN.",
    move: "BOUGER", aim: "VISER", attack: "ATTAQUER", dash: "DASH", swap: "CHANGER D'ARME", shop: "BOUTIQUE",
    moveHelp: "ZQSD/WASD ou flèches", aimHelp: "Bougez la souris", attackHelp: "M1, Espace ou J", dashHelp: "Shift, K ou clic droit",
    swapHelp: "1-4, Q/E ou molette", shopHelp: "S'ouvre après chaque vague. Dépensez vos pièces avant de continuer.",
    touchMove: "JOYSTICK GAUCHE", touchAim: "TOUCHEZ À DROITE", touchAttack: "MAINTENEZ À DROITE", touchDash: "BOUTON DASH", touchSwap: "TOUCHEZ UN SLOT",
    tutorialTitle: "COMMENT SURVIVRE", tutorialLead: "Apprenez ces commandes avant la première vague.",
    dontShow: "NE PLUS AFFICHER", begin: "COMMENCER LA VAGUE 1", shopSoon: "BOUTIQUE APRÈS LA VAGUE",
    upgrades: "AMÉLIORATIONS D'ARME", damage: "DÉGÂTS", speed: "VIT. ATTAQUE", range: "PORTÉE", form: "FORME",
    level: "NIV.", max: "MAX", improve: "AMÉLIORER", evolved: "ÉVOLUÉE", formLocked: "SEULS LE KATANA, L'ARC, LE MARTEAU ET LE LIVRE ÉVOLUENT",
    book: "LIVRE ARCANIQUE", bookDesc: "Lance une magie en cône. Choisissez un élément.", staff: "BATON D INVOCATION", staffDesc: "Invoque des alliés bleus et ressuscite des ennemis.", necromancerStaff: "BATON NECROMANT",
    magic: "MAGIE", fire: "FEU", fireDesc: "Forts dégâts et brûlure. Courte portée.",
    ice: "GLACE", iceDesc: "Très peu de dégâts; gèle 2 s puis ralentit 5 s.",
    poison: "POISON", poisonDesc: "Faible impact, dégâts massifs sur la durée.",
    water: "EAU", waterDesc: "Faibles dégâts et forte répulsion.",
    shieldHint: "BLOQUE ET REPOUSSE VERS LA VISÉE. M1 RENVOIE LES PROJECTILES.",
    weaponLevel: "NIVEAU D'ARME", automaticPistol: "PISTOLET AUTOMATIQUE", titanHammer: "MARTEAU TITAN",
  },
  de: {
    menuLead: "BEHERRSCHE DIE ARENA, VERBESSERE DEIN ARSENAL UND ÜBERLEBE DEN SHOGUN.",
    move: "BEWEGEN", aim: "ZIELEN", attack: "ANGREIFEN", dash: "DASH", swap: "WAFFE WECHSELN", shop: "LADEN",
    moveHelp: "WASD oder Pfeile", aimHelp: "Maus bewegen", attackHelp: "M1, Leertaste oder J", dashHelp: "Shift, K oder Rechtsklick",
    swapHelp: "1-4, Q/E oder Mausrad", shopHelp: "Öffnet nach jeder Welle. Gib Münzen vor der nächsten Welle aus.",
    touchMove: "LINKER JOYSTICK", touchAim: "RECHTS BERÜHREN", touchAttack: "RECHTS HALTEN", touchDash: "DASH-TASTE", touchSwap: "SLOT ANTIPPEN",
    tutorialTitle: "SO ÜBERLEBST DU", tutorialLead: "Lerne diese Steuerung vor der ersten Welle.",
    dontShow: "NICHT MEHR ZEIGEN", begin: "WELLE 1 STARTEN", shopSoon: "LADEN NACH DER WELLE",
    upgrades: "WAFFEN-UPGRADES", damage: "SCHADEN", speed: "ANGRIFFSTEMPO", range: "REICHWEITE", form: "FORM",
    level: "ST.", max: "MAX", improve: "VERBESSERN", evolved: "ENTWICKELT", formLocked: "NUR KATANA, BOGEN, HAMMER, BUCH UND STAB ENTWICKELN SICH",
    book: "ARKANES BUCH", bookDesc: "Wirkt Magie in einem Kegel. Wähle ein Element.", staff: "BESCHWÖRUNGSSTAB", staffDesc: "Beschwört blaue Verbündete und belebt Feinde wieder.", necromancerStaff: "NEKROMANTENSTAB",
    magic: "MAGIE", fire: "FEUER", fireDesc: "Hoher Treffer- und Brandschaden. Kurze Reichweite.",
    ice: "EIS", iceDesc: "Kaum Schaden; friert 2 s ein und verlangsamt 5 s.",
    poison: "GIFT", poisonDesc: "Wenig Trefferschaden, massiver Zeitschaden.",
    water: "WASSER", waterDesc: "Wenig Schaden und starker Rückstoß.",
    shieldHint: "BLOCKT UND STÖSST IN ZIELRICHTUNG. M1 REFLEKTIERT PROJEKTILE.",
    weaponLevel: "WAFFENSTUFE", automaticPistol: "AUTOMATISCHE PISTOLE", titanHammer: "TITANHAMMER",
  },
  zh: {
    menuLead: "掌控竞技场，强化武器库，并在将军面前生存下来。",
    move: "移动", aim: "瞄准", attack: "攻击", dash: "冲刺", swap: "切换武器", shop: "商店",
    moveHelp: "WASD或方向键", aimHelp: "移动鼠标", attackHelp: "鼠标左键、空格或J", dashHelp: "Shift、K或鼠标右键",
    swapHelp: "1-4、Q/E或滚轮", shopHelp: "每波结束后开启。继续前使用金币强化。",
    touchMove: "左侧摇杆", touchAim: "触摸右侧瞄准", touchAttack: "按住右侧攻击", touchDash: "冲刺按钮", touchSwap: "点击武器栏",
    tutorialTitle: "生存指南", tutorialLead: "第一波开始前请熟悉这些操作。",
    dontShow: "不再显示", begin: "开始第1波", shopSoon: "每波后开启商店",
    upgrades: "武器强化", damage: "伤害", speed: "攻击速度", range: "范围", form: "形态",
    level: "等级", max: "最高", improve: "强化", evolved: "已进化", formLocked: "只有武士刀、弓、锤、法书和法杖可以进化",
    book: "奥术之书", bookDesc: "向锥形范围施放魔法。选择元素控制战场。", staff: "召唤法杖", staffDesc: "召唤蓝色盟友并复活敌人。", necromancerStaff: "死灵法杖",
    magic: "魔法", fire: "火焰", fireDesc: "高接触伤害与灼烧，范围较短。",
    ice: "寒冰", iceDesc: "伤害极低；冻结2秒，之后减速5秒。",
    poison: "毒素", poisonDesc: "接触伤害低，但持续伤害极高。",
    water: "水流", waterDesc: "伤害低，可强力击退敌人。",
    shieldHint: "朝瞄准方向格挡并击退。鼠标左键反射投射物。",
    weaponLevel: "武器等级", automaticPistol: "自动手枪", titanHammer: "泰坦巨锤",
  },
} as const satisfies Record<Language, Record<string, string>>;

export type GameplayStrings = (typeof GAMEPLAY_TEXT)[Language];
