import type { Language } from "./i18n";
import type { Weapon } from "./audio";
import type { Perk } from "./perks";

const WEAPONS: Record<Language, Partial<Record<Weapon, [string, string]>>> = {
  pt: { harp:["ARPA DIVINA","Cura e chicoteia em três direções."], godslayer:["GODSLAYER","Lâmina divina de dano e alcance extremos."], boomerang:["BUMERANGUE","Procura inimigos e retorna ao jogador; só pode haver um em voo."], shuriken:["SHURIKEN","Projétil rápido; a evolução explode ao primeiro impacto."], spear:["LANÇA","Ataque lento e brutal cuja haste inteira acerta até a ponta."] },
  en: { harp:["DIVINE HARP","Heals and lashes in three directions."], godslayer:["GODSLAYER","Divine blade with extreme damage and reach."], boomerang:["BOOMERANG","Seeks five nearby enemies and returns to the player."], shuriken:["SHURIKEN","A fast, light, long-range projectile."], spear:["SPEAR","A slow, brutal thrust that only hits with its tip."] },
  fr: { harp:["HARPE DIVINE","Soigne et frappe dans trois directions."], godslayer:["GODSLAYER","Lame divine aux dégâts et à la portée extrêmes."], boomerang:["BOOMERANG","Cherche cinq ennemis proches puis revient."], shuriken:["SHURIKEN","Projectile rapide, léger et de longue portée."], spear:["LANCE","Frappe lente et brutale uniquement avec la pointe."] },
  de: { harp:["GÖTTLICHE HARFE","Heilt und schlägt in drei Richtungen."], godslayer:["GODSLAYER","Göttliche Klinge mit extremem Schaden und Reichweite."], boomerang:["BUMERANG","Sucht fünf nahe Gegner und kehrt zurück."], shuriken:["SHURIKEN","Schnelles, leichtes Projektil mit hoher Reichweite."], spear:["SPEER","Langsamer, brutaler Stoß, der nur mit der Spitze trifft."] },
  zh: { harp:["神圣竖琴","治疗自身并向三个方向攻击。"], godslayer:["弑神者","拥有极高伤害与攻击距离的神圣刀刃。"], boomerang:["回旋镖","追踪五名附近敌人后返回玩家。"], shuriken:["手里剑","快速、轻巧且射程很远的投射物。"], spear:["长枪","缓慢而强力，只有枪尖能够命中。"] },
};

export function localizedWeapon(language: Language, weapon: Weapon) { return WEAPONS[language][weapon]; }

export const SHOP_UI = {
  pt:{choose:"ESCOLHA UMA CATEGORIA",back:"VOLTAR",weapons:"ARMAS",weaponsDesc:"Compre, venda e organize seus slots.",stats:"ESTATÍSTICAS",statsDesc:"Melhore vida, velocidade e dash.",upgrades:"UPGRADES",upgradesDesc:"Evolua apenas as armas possuídas.",character:"PERSONAGEM",characterDesc:"Abra a ficha completa da run.",slots:"SLOTS · ARRASTE PARA TROCAR",owned:"ARMAS POSSUÍDAS",evolution:"EVOLUÇÃO"},
  en:{choose:"CHOOSE A CATEGORY",back:"BACK",weapons:"WEAPONS",weaponsDesc:"Buy, sell, and organize your slots.",stats:"STATS",statsDesc:"Improve health, speed, and dash.",upgrades:"UPGRADES",upgradesDesc:"Upgrade weapons you own.",character:"CHARACTER",characterDesc:"Open the complete run sheet.",slots:"SLOTS · DRAG TO REORDER",owned:"OWNED WEAPONS",evolution:"EVOLUTION"},
  fr:{choose:"CHOISISSEZ UNE CATÉGORIE",back:"RETOUR",weapons:"ARMES",weaponsDesc:"Achetez, vendez et organisez vos emplacements.",stats:"STATISTIQUES",statsDesc:"Améliorez vie, vitesse et dash.",upgrades:"AMÉLIORATIONS",upgradesDesc:"Améliorez les armes possédées.",character:"PERSONNAGE",characterDesc:"Ouvrez la fiche complète de la partie.",slots:"EMPLACEMENTS · GLISSEZ POUR TRIER",owned:"ARMES POSSÉDÉES",evolution:"ÉVOLUTION"},
  de:{choose:"KATEGORIE WÄHLEN",back:"ZURÜCK",weapons:"WAFFEN",weaponsDesc:"Kaufen, verkaufen und Plätze ordnen.",stats:"WERTE",statsDesc:"Leben, Tempo und Dash verbessern.",upgrades:"VERBESSERUNGEN",upgradesDesc:"Eigene Waffen verbessern.",character:"CHARAKTER",characterDesc:"Vollständige Run-Werte öffnen.",slots:"PLÄTZE · ZUM SORTIEREN ZIEHEN",owned:"EIGENE WAFFEN",evolution:"ENTWICKLUNG"},
  zh:{choose:"选择类别",back:"返回",weapons:"武器",weaponsDesc:"购买、出售并整理武器栏。",stats:"属性",statsDesc:"提升生命、速度和冲刺。",upgrades:"强化",upgradesDesc:"强化已拥有的武器。",character:"角色",characterDesc:"查看本局完整属性。",slots:"武器栏·拖动排序",owned:"已拥有武器",evolution:"进化"},
} as const;

export const MENU_UI = {
  pt:{perkTitle:"ESCOLHA SUA PERK",perkLead:"Escolha uma vantagem para esta partida.",back:"VOLTAR",coop:"COOPERATIVO",profile:"PERFIL",loginCoop:"Faça login ou crie uma conta para jogar no modo cooperativo."},
  en:{perkTitle:"CHOOSE YOUR PERK",perkLead:"Choose one advantage for this run.",back:"BACK",coop:"CO-OP",profile:"PROFILE",loginCoop:"Sign in or create an account to play co-op."},
  fr:{perkTitle:"CHOISISSEZ VOTRE PERK",perkLead:"Choisissez un avantage pour cette partie.",back:"RETOUR",coop:"COOPÉRATIF",profile:"PROFIL",loginCoop:"Connectez-vous ou créez un compte pour jouer en coopération."},
  de:{perkTitle:"PERK WÄHLEN",perkLead:"Wähle einen Vorteil für diesen Run.",back:"ZURÜCK",coop:"KOOP",profile:"PROFIL",loginCoop:"Melde dich an oder erstelle ein Konto für den Koop-Modus."},
  zh:{perkTitle:"选择特性",perkLead:"为本局选择一项优势。",back:"返回",coop:"合作模式",profile:"个人资料",loginCoop:"登录或创建账号后即可游玩合作模式。"},
} as const;

export const PERK_TEXT: Record<Language, Record<Perk, [string,string]>> = {
  pt:{bladeMonk:["MONGE DA LÂMINA ÚNICA","Somente katana: +85% dano, +35% ataque e dash 20% mais rápido."],bloodContract:["CONTRATO DE SANGUE","Abaixo de 30% de vida: +75% dano e +35% ataque."],bottomlessPocket:["BOLSO SEM FUNDO","Seis slots de arma, mas -12 de velocidade."],predatorInstinct:["INSTINTO PREDADOR","Abates concedem movimento e ataque por 2,5s."],sharpGlass:["VIDRO AFIADO","+35% dano, mas começa com 3 corações."],kyuEcho:["ECO DE KYU","A cada 6s, o próximo ataque causa +65% dano."],cursedArsenal:["ARSENAL AMALDIÇOADO","+20% dano para todo o arsenal, mas -8 velocidade."],lastBullet:["ÚLTIMA BALA","Tiros especiais do arco e pistola causam +100% dano."]},
  en:{bladeMonk:["SINGLE BLADE MONK","Katana only: +85% damage, +35% attack speed, 20% faster dash cooldown."],bloodContract:["BLOOD CONTRACT","Below 30% health: +75% damage and +35% attack speed."],bottomlessPocket:["BOTTOMLESS POCKET","Six weapon slots, but -12 movement speed."],predatorInstinct:["PREDATOR INSTINCT","Kills grant movement and attack speed for 2.5s."],sharpGlass:["SHARP GLASS","+35% damage, but starts with 3 hearts."],kyuEcho:["ECHO OF KYU","Every 6s, the next attack deals +65% damage."],cursedArsenal:["CURSED ARSENAL","+20% damage for every weapon, but -8 speed."],lastBullet:["LAST BULLET","Special bow and pistol shots deal +100% damage."]},
  fr:{bladeMonk:["MOINE DE LA LAME UNIQUE","Katana uniquement : +85% dégâts, +35% vitesse d'attaque et dash rechargé 20% plus vite."],bloodContract:["PACTE DE SANG","Sous 30% de vie : +75% dégâts et +35% vitesse d'attaque."],bottomlessPocket:["POCHE SANS FOND","Six emplacements d'arme, mais -12 vitesse."],predatorInstinct:["INSTINCT PRÉDATEUR","Les éliminations augmentent mouvement et attaque pendant 2,5 s."],sharpGlass:["VERRE TRANCHANT","+35% dégâts, mais commence avec 3 cœurs."],kyuEcho:["ÉCHO DE KYU","Toutes les 6 s, la prochaine attaque inflige +65% dégâts."],cursedArsenal:["ARSENAL MAUDIT","+20% dégâts pour tout l'arsenal, mais -8 vitesse."],lastBullet:["DERNIÈRE BALLE","Les tirs spéciaux de l'arc et du pistolet infligent +100% dégâts."]},
  de:{bladeMonk:["MÖNCH DER EINZELNEN KLINGE","Nur Katana: +85% Schaden, +35% Angriffstempo und 20% schnellere Dash-Aufladung."],bloodContract:["BLUTVERTRAG","Unter 30% Leben: +75% Schaden und +35% Angriffstempo."],bottomlessPocket:["BODENLOSE TASCHE","Sechs Waffenplätze, aber -12 Tempo."],predatorInstinct:["RAUBTIERINSTINKT","Besiegte Gegner geben 2,5 s Bewegungs- und Angriffstempo."],sharpGlass:["SCHARFES GLAS","+35% Schaden, beginnt aber mit 3 Herzen."],kyuEcho:["ECHO VON KYU","Alle 6 s verursacht der nächste Angriff +65% Schaden."],cursedArsenal:["VERFLUCHTES ARSENAL","+20% Schaden für alle Waffen, aber -8 Tempo."],lastBullet:["LETZTE KUGEL","Spezielle Bogen- und Pistolenschüsse verursachen +100% Schaden."]},
  zh:{bladeMonk:["独刃武僧","只能使用武士刀：伤害+85%，攻速+35%，冲刺冷却加快20%。"],bloodContract:["血之契约","生命低于30%时：伤害+75%，攻速+35%。"],bottomlessPocket:["无底口袋","武器栏增加到六格，但速度-12。"],predatorInstinct:["掠食本能","击杀后获得2.5秒移动和攻击速度加成。"],sharpGlass:["锋利玻璃","伤害+35%，但初始只有3颗心。"],kyuEcho:["KYU回响","每6秒，下一次攻击伤害+65%。"],cursedArsenal:["诅咒武库","所有武器伤害+20%，但速度-8。"],lastBullet:["最后一弹","弓与手枪的特殊射击伤害+100%。"]},
};
