import type { Weapon } from "./audio";

export type RaceId = "divinity" | "human" | "oni" | "elf" | "dwarf" | "giant" | "orc" | "goblin" | "draconic" | "godHunter" | "oniBlood" | "spiritualHeir" | "ronin" | "survivor";
export type RaceRarity = "divine" | "mythic" | "legendary" | "epic" | "blue" | "uncommon" | "common";
export type RaceAbilityKind = "buff" | "divine" | "flame";

export interface RaceConfig {
  id: RaceId; name: string; rarity: RaceRarity; description: string; passive: string; icon: string; color: string; weight: number;
  startingWeapons?: Weapon[]; bonusWeaponSlots?: number; playerScale?: number; coinMultiplier?: number; rangedDamage?: number;
  floorHeal?: number; killDamageStep?: number; killDamageCap?: number; silverHearts?: boolean; willChance?: number;
  modifiers: { damage: number; maxHp: number; moveSpeed: number; dashCooldown: number; attackSpeed: number; attributeLimit: number; initialProgress: number; };
  ability: { kind: RaceAbilityKind; name: string; description: string; duration: number; cooldown: number; damage: number; moveSpeed: number; dashCooldown: number; attackSpeed: number; invulnerable: boolean; contactImmune: boolean; healMaxHpFraction: number; };
}

const ability = (overrides: Partial<RaceConfig["ability"]>): RaceConfig["ability"] => ({ kind:"buff", name:"", description:"", duration:0, cooldown:30, damage:1, moveSpeed:1, dashCooldown:1, attackSpeed:1, invulnerable:false, contactImmune:false, healMaxHpFraction:0, ...overrides });
const modifiers = (overrides: Partial<RaceConfig["modifiers"]>): RaceConfig["modifiers"] => ({ damage:1, maxHp:1, moveSpeed:1, dashCooldown:1, attackSpeed:1, attributeLimit:1, initialProgress:0, ...overrides });

export const RACE_CONFIG: Record<RaceId, RaceConfig> = {
  divinity: { id:"divinity", name:"DIVINITY / GOD", rarity:"divine", description:"Uma existência celestial quase impossível de encontrar.", passive:"Nasce com Arpa em um slot extra e tem 10% de chance de também receber Godslayer.", icon:"✧", color:"#ffffff", weight:0.1, startingWeapons:["harp"], bonusWeaponSlots:1, modifiers:modifiers({damage:1.18,maxHp:1.2,moveSpeed:1.08}), ability:ability({kind:"divine",name:"ASCENSÃO",description:"80%: Wings concede voo e i-frame por 3,5s. 20%: Aura ajoelha inimigos e pune os mais próximos.",duration:3.5,cooldown:38}) },
  human: { id:"human", name:"HUMANO", rarity:"common", description:"Adaptável e persistente.", passive:"10% de chance de despertar Will: uma segunda chance com +20% de dano.", icon:"●", color:"#c9ced4", weight:10, willChance:.1, modifiers:modifiers({}), ability:ability({name:"DETERMINAÇÃO",description:"Recupera 15% da vida máxima.",cooldown:42,healMaxHpFraction:.15}) },
  oni: { id:"oni", name:"ONI", rarity:"epic", description:"Demônio guerreiro que cresce com cada abate.", passive:"Recupera 1 coração ao fim de cada floor e ganha 0,1% de dano por abate, até +50%.", icon:"鬼", color:"#a855f7", weight:4, floorHeal:1, killDamageStep:.001, killDamageCap:.5, modifiers:modifiers({damage:1.12}), ability:ability({name:"RAGE",description:"Explode em fúria: +35% dano e +15% velocidade por 6s.",duration:6,cooldown:34,damage:1.35,moveSpeed:1.15}) },
  elf: { id:"elf", name:"ELFO", rarity:"blue", description:"Especialista em precisão e combate à distância.", passive:"Começa com Arco em slot extra, +20% alcance geral e +35% dano à distância.", icon:"➶", color:"#67d9ef", weight:8, startingWeapons:["bow"], bonusWeaponSlots:1, rangedDamage:1.35, modifiers:modifiers({moveSpeed:1.08}), ability:ability({name:"SENTIDO ÉLFICO",description:"+30% ataque e movimento por 5s.",duration:5,cooldown:30,attackSpeed:1.3,moveSpeed:1.2}) },
  dwarf: { id:"dwarf", name:"ANÃO", rarity:"uncommon", description:"Pequeno, robusto e cada vez mais difícil de derrubar.", passive:"+2 corações. Cada coração perdido fortalece a resistência; os corações evoluem para prata e ouro.", icon:"◆", color:"#8be28b", weight:17, playerScale:.9, modifiers:modifiers({maxHp:1.4,moveSpeed:.92}), ability:ability({name:"FORTALEZA",description:"Reduz o dano recebido pela metade por 5s.",duration:5,cooldown:40}) },
  giant: { id:"giant", name:"GIGANTE", rarity:"epic", description:"Corpo colossal, golpes brutais e mobilidade baixa.", passive:"+5 corações, +45% dano e -35% velocidade. Corpo e hitbox maiores.", icon:"▰", color:"#a855f7", weight:4, playerScale:1.45, modifiers:modifiers({maxHp:2,damage:1.45,moveSpeed:.65,attackSpeed:.88}), ability:ability({name:"PISÃO",description:"Golpes e movimento ficam mais fortes por 5s.",duration:5,cooldown:38,damage:1.25,moveSpeed:1.2}) },
  orc: { id:"orc", name:"ORC", rarity:"uncommon", description:"Força direta sem truques.", passive:"+40% de dano, compensado por ataques 8% mais lentos.", icon:"▲", color:"#8be28b", weight:11, modifiers:modifiers({damage:1.4,attackSpeed:.92}), ability:ability({name:"GRITO DE GUERRA",description:"+25% dano por 6s.",duration:6,cooldown:36,damage:1.25}) },
  goblin: { id:"goblin", name:"GOBLIN", rarity:"common", description:"Rápido, ganancioso e frágil.", passive:"+75% moedas, +25% velocidade e -1 coração inicial.", icon:"¤", color:"#c9ced4", weight:12, coinMultiplier:1.75, playerScale:.82, modifiers:modifiers({maxHp:.8,moveSpeed:1.25}), ability:ability({name:"FUGA",description:"+45% movimento e dash rápido por 4s.",duration:4,cooldown:28,moveSpeed:1.45,dashCooldown:.45}) },
  draconic: { id:"draconic", name:"DRACÔNICO", rarity:"legendary", description:"Sangue de dragão, resistente e incendiário.", passive:"+35% dano e corações prateados: cada coração suporta dois golpes equivalentes.", icon:"♨", color:"#ffd21f", weight:4, silverHearts:true, modifiers:modifiers({damage:1.35}), ability:ability({kind:"flame",name:"FLAME",description:"Sopra fogo em longo alcance, causando dano alto e queimadura.",duration:1.2,cooldown:24}) },
  godHunter: { id:"godHunter", name:"CAÇADOR DE DEUSES", rarity:"mythic", description:"Poder divino rompe limites de progressão.", passive:"+70% dano e atributos podem avançar além dos limites normais.", icon:"✦", color:"#ef4444", weight:0.9, modifiers:modifiers({damage:1.7,attributeLimit:1.5,initialProgress:.25}), ability:ability({name:"IMORTALIDADE",description:"Ignora dano por 4s.",duration:4,cooldown:44,invulnerable:true}) },
  oniBlood: { id:"oniBlood", name:"SANGUE ONI", rarity:"epic", description:"Linhagem agressiva que troca resistência por força.", passive:"+22% dano e -10% vida máxima.", icon:"鬼", color:"#a855f7", weight:4, modifiers:modifiers({damage:1.22,maxHp:.9}), ability:ability({name:"FÚRIA ONI",description:"+35% dano e +20% movimento por 6s.",duration:6,cooldown:32,damage:1.35,moveSpeed:1.2}) },
  spiritualHeir: { id:"spiritualHeir", name:"HERDEIRO ESPIRITUAL", rarity:"blue", description:"Mobilidade sobrenatural.", passive:"-20% recarga de dash e +10% movimento.", icon:"◇", color:"#67d9ef", weight:9, modifiers:modifiers({moveSpeed:1.1,dashCooldown:.8}), ability:ability({name:"PASSO ESPIRITUAL",description:"Mobilidade extrema e imunidade de contato por 4s.",duration:4,cooldown:27,moveSpeed:1.6,dashCooldown:.3,contactImmune:true}) },
  ronin: { id:"ronin", name:"RONIN", rarity:"common", description:"Equilibrado e preparado para qualquer arma.", passive:"+8% dano e +5% movimento.", icon:"刀", color:"#c9ced4", weight:4, modifiers:modifiers({damage:1.08,moveSpeed:1.05}), ability:ability({name:"FOCO",description:"+20% dano e +15% ataque por 5s.",duration:5,cooldown:30,damage:1.2,attackSpeed:1.15}) },
  survivor: { id:"survivor", name:"SOBREVIVENTE", rarity:"common", description:"Resistência simples para momentos críticos.", passive:"+10% vida máxima.", icon:"♥", color:"#c9ced4", weight:14, modifiers:modifiers({maxHp:1.1}), ability:ability({name:"SEGUNDO FÔLEGO",description:"Recupera 20% da vida máxima.",cooldown:35,healMaxHpFraction:.2}) },
};

export const RACE_IDS = Object.keys(RACE_CONFIG) as RaceId[];
let forcedRace: RaceId | null = null;
export function forceRace(race: RaceId | null) { forcedRace = race; }
export function isRaceId(value: unknown): value is RaceId { return typeof value === "string" && value in RACE_CONFIG; }
export function rollRace(random = Math.random): RaceId { if(forcedRace)return forcedRace; let roll=Math.max(0,Math.min(.999999999,random()))*100; for(const id of RACE_IDS){ roll-=RACE_CONFIG[id].weight; if(roll<0)return id; } return "human"; }
export function raceRarityLabel(rarity: RaceRarity) { return rarity === "divine" ? "DIVINA" : rarity === "mythic" ? "MÍTICA" : rarity === "legendary" ? "LENDÁRIA" : rarity === "epic" ? "ÉPICA" : rarity === "blue" ? "AZUL" : rarity === "uncommon" ? "INCOMUM" : "COMUM"; }