import type { Language } from "./i18n";

type UiKey = "inputTitle" | "inputLead" | "keyboard" | "keyboardMouse" | "gamepad" | "keyboardDesc" | "keyboardMouseDesc" | "gamepadDesc" | "inputHint" | "raceObtained" | "continue" | "hideForever" | "coopEnded" | "coopBanner" | "saveScore" | "saving" | "noScoresDifficulty" | "waitingAllies" | "tryAgain" | "coopNote";

const TEXT: Record<Language, Record<UiKey, string>> = {
  pt: { inputTitle:"COMO VOCÊ VAI JOGAR?", inputLead:"Escolha o layout de controle desta partida.", keyboard:"TECLADO", keyboardMouse:"TECLADO + MOUSE", gamepad:"CONTROLE", keyboardDesc:"Mover, atacar e usar dash pelo teclado.", keyboardMouseDesc:"Teclado para mover e mouse para mirar e atacar.", gamepadDesc:"Xbox e PlayStation: analógicos, A/✕, RB/R1 e RT/R2.", inputHint:"Use as setas e ENTER, ou o direcional e A, para escolher.", raceObtained:"RAÇA OBTIDA", continue:"CONTINUAR", hideForever:"NÃO MOSTRAR NOVAMENTE", coopEnded:"PARTIDA COOP ENCERRADA", coopBanner:"MODO COOPERATIVO · RANKING DESATIVADO", saveScore:"SALVANDO...", saving:"SALVANDO...", noScoresDifficulty:"SEM RECORDES NESTA DIFICULDADE", waitingAllies:"AGUARDANDO ALIADOS...", tryAgain:"TENTAR NOVAMENTE", coopNote:"Todos precisam confirmar. A equipe voltará ao mesmo lobby e código." },
  en: { inputTitle:"HOW WILL YOU PLAY?", inputLead:"Choose the control layout for this run.", keyboard:"KEYBOARD", keyboardMouse:"KEYBOARD + MOUSE", gamepad:"GAMEPAD", keyboardDesc:"Move, attack, and dash with the keyboard.", keyboardMouseDesc:"Move with the keyboard and aim/attack with the mouse.", gamepadDesc:"Xbox and PlayStation: sticks, A/✕, RB/R1, and RT/R2.", inputHint:"Use the arrows and ENTER, or the D-pad and A, to choose.", raceObtained:"RACE ACQUIRED", continue:"CONTINUE", hideForever:"DO NOT SHOW AGAIN", coopEnded:"CO-OP RUN OVER", coopBanner:"CO-OP MODE · RANKING DISABLED", saveScore:"SAVING...", saving:"SAVING...", noScoresDifficulty:"NO SCORES FOR THIS DIFFICULTY", waitingAllies:"WAITING FOR ALLIES...", tryAgain:"TRY AGAIN", coopNote:"Everyone must confirm. The team will return to the same lobby and code." },
  fr: { inputTitle:"COMMENT JOUER ?", inputLead:"Choisissez la disposition des commandes.", keyboard:"CLAVIER", keyboardMouse:"CLAVIER + SOURIS", gamepad:"MANETTE", keyboardDesc:"Déplacez-vous, attaquez et faites un dash au clavier.", keyboardMouseDesc:"Clavier pour bouger, souris pour viser et attaquer.", gamepadDesc:"Xbox et PlayStation : sticks, A/✕, RB/R1 et RT/R2.", inputHint:"Utilisez les flèches et ENTRÉE, ou la croix et A.", raceObtained:"RACE OBTENUE", continue:"CONTINUER", hideForever:"NE PLUS AFFICHER", coopEnded:"PARTIE COOP TERMINÉE", coopBanner:"MODE COOP · CLASSEMENT DÉSACTIVÉ", saveScore:"ENREGISTREMENT...", saving:"ENREGISTREMENT...", noScoresDifficulty:"AUCUN SCORE POUR CETTE DIFFICULTÉ", waitingAllies:"EN ATTENTE DES ALLIÉS...", tryAgain:"RÉESSAYER", coopNote:"Tout le monde doit confirmer. L'équipe reviendra au même lobby et code." },
  de: { inputTitle:"WIE MÖCHTEST DU SPIELEN?", inputLead:"Wähle die Steuerung für diesen Lauf.", keyboard:"TASTATUR", keyboardMouse:"TASTATUR + MAUS", gamepad:"CONTROLLER", keyboardDesc:"Bewegen, angreifen und dashen mit der Tastatur.", keyboardMouseDesc:"Mit der Tastatur bewegen, mit der Maus zielen und angreifen.", gamepadDesc:"Xbox und PlayStation: Sticks, A/✕, RB/R1 und RT/R2.", inputHint:"Nutze Pfeile und ENTER oder Steuerkreuz und A.", raceObtained:"RASSE ERHALTEN", continue:"FORTSETZEN", hideForever:"NICHT MEHR ZEIGEN", coopEnded:"COOP-RUN BEENDET", coopBanner:"COOP-MODUS · RANGLISTE DEAKTIVIERT", saveScore:"SPEICHERN...", saving:"SPEICHERN...", noScoresDifficulty:"NOCH KEINE ERGEBNISSE", waitingAllies:"WARTE AUF VERBÜNDETE...", tryAgain:"NOCHMAL VERSUCHEN", coopNote:"Alle müssen bestätigen. Das Team kehrt zur gleichen Lobby und zum gleichen Code zurück." },
  zh: { inputTitle:"你要如何游玩？", inputLead:"选择本局的控制方式。", keyboard:"键盘", keyboardMouse:"键盘 + 鼠标", gamepad:"手柄", keyboardDesc:"使用键盘移动、攻击和冲刺。", keyboardMouseDesc:"键盘移动，鼠标瞄准和攻击。", gamepadDesc:"Xbox和PlayStation：摇杆、A/✕、RB/R1和RT/R2。", inputHint:"使用方向键和回车，或方向键和A进行选择。", raceObtained:"获得种族", continue:"继续", hideForever:"不再显示", coopEnded:"合作游戏结束", coopBanner:"合作模式 · 排行榜已禁用", saveScore:"保存中...", saving:"保存中...", noScoresDifficulty:"该难度暂无记录", waitingAllies:"等待队友...", tryAgain:"再试一次", coopNote:"所有人都需要确认。队伍将返回相同的大厅和代码。" },
};
export function uiText(language: Language, key: UiKey) { return TEXT[language][key]; }