import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/vitor/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:1800,height:1400},deviceScaleFactor:1});
const pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));
await page.goto('http://127.0.0.1:5173/artifacts/kyuneth-13/characters.html');
await page.waitForFunction(()=>window.ready);
const report=await page.evaluate(()=>window.report);
report.errors.push(...pageErrors);
const controls=await page.evaluate(async()=>{
  const {humanFrame}=await import('/src/story/characters/renderer.ts');
  const base=humanFrame('player','down',false,0);
  const gaze=humanFrame('player','down',false,0,{gaze:{x:1,y:0}});
  const empty=document.createElement('canvas');empty.width=56;empty.height=64;
  const hair=humanFrame('player','down',false,0,{parts:{hair:empty}});
  return {gazeChangesFrame:base.toDataURL()!==gaze.toDataURL(),partOverrideChangesFrame:base.toDataURL()!==hair.toDataURL()};
});
report.controls=controls;
if(!controls.gazeChangesFrame||!controls.partOverrideChangesFrame)report.errors.push('independent protagonist controls did not change the frame');
fs.writeFileSync('artifacts/kyuneth-13/report.json',JSON.stringify(report,null,2));
await page.screenshot({path:'artifacts/kyuneth-13/all-characters.png'});
await page.screenshot({path:'artifacts/kyuneth-13/protagonist.png',clip:{x:0,y:0,width:1800,height:150}});
await page.screenshot({path:'artifacts/kyuneth-13/residents.png',clip:{x:0,y:150,width:1800,height:910}});
await page.screenshot({path:'artifacts/kyuneth-13/animals.png',clip:{x:0,y:1060,width:1800,height:330}});
await browser.close();
console.log(JSON.stringify({characters:report.characters,directions:report.directions,errors:report.errors}));
if(report.errors.length)process.exitCode=1;